### index handler
GET http://localhost:8080

### list todos handler
GET http://localhost:8080/todos

### login handler
POST http://localhost:8080/login
Content-Type: application/json

{
    "email": "Meng@123.com",
    "password": "hunter42"
}


### create todo handler
POST http://localhost:8080/todos
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibmFtZSI6IlRlYW0gTWVuZyIsImV4cCI6MTcyOTQ4NjYxNH0.YibD09lLtHYiKaFeXmmaxhQP2J3YnyzKvP2R46N6kOo

{
    "title": "Todo 3"
}
